In [1]:
import pandas as pd

In [2]:
import numpy as np

In [5]:
df = pd.read_csv("Datafiniti_Hotel_Reviews.csv")

In [6]:
df.head()

id             dateAdded           dateUpdated  \
0  AVwc252WIN2L1WUfpqLP  2016-10-30T21:42:42Z  2018-09-10T21:06:27Z   
1  AVwc252WIN2L1WUfpqLP  2016-10-30T21:42:42Z  2018-09-10T21:06:27Z   
2  AVwc252WIN2L1WUfpqLP  2016-10-30T21:42:42Z  2018-09-10T21:06:27Z   
3  AVwdOclqIN2L1WUfti38  2015-11-28T19:19:35Z  2018-09-10T21:06:16Z   
4  AVwdOclqIN2L1WUfti38  2015-11-28T19:19:35Z  2018-09-10T21:06:16Z   

             address                                         categories  \
0  5921 Valencia Cir  Hotels,Hotels and motels,Hotel and motel reser...   
1  5921 Valencia Cir  Hotels,Hotels and motels,Hotel and motel reser...   
2  5921 Valencia Cir  Hotels,Hotels and motels,Hotel and motel reser...   
3     7520 Teague Rd  Hotels,Hotels and motels,Travel agencies and b...   
4     7520 Teague Rd  Hotels,Hotels and motels,Travel agencies and b...   

               primaryCategories             city country  \
0  Accommodation & Food Services  Rancho Santa Fe      US   
1  Accommodation & Food Services  Rancho Santa Fe      US   
2  Accommodation & Food Services  Rancho Santa Fe      US   
3  Accommodation & Food Services          Hanover      US   
4  Accommodation & Food Services          Hanover      US   

                                            keys   latitude  \
0  us/ca/ranchosantafe/5921valenciacir/359754519  32.990959   
1  us/ca/ranchosantafe/5921valenciacir/359754519  32.990959   
2  us/ca/ranchosantafe/5921valenciacir/359754519  32.990959   
3         us/md/hanover/7520teaguerd/-2043779672  39.155929   
4         us/md/hanover/7520teaguerd/-2043779672  39.155929   

                         ...                          \
0                        ...                           
1                        ...                           
2                        ...                           
3                        ...                           
4                        ...                           

                                    reviews.dateSeen reviews.rating  \
0  2016-08-03T00:00:00Z,2016-07-26T00:00:00Z,2016...            5.0   
1  2016-08-02T00:00:00Z,2016-08-26T00:00:00Z,2016...            5.0   
2  2016-11-15T00:00:00Z,2016-08-23T00:00:00Z,2016...            5.0   
3          2016-05-21T00:00:00Z,2016-07-31T00:00:00Z            2.0   
4                               2016-07-31T00:00:00Z            5.0   

                                  reviews.sourceURLs  \
0    https://www.hotels.com/hotel/125419/reviews%20/   
1    https://www.hotels.com/hotel/125419/reviews%20/   
2    https://www.hotels.com/hotel/125419/reviews%20/   
3  https://www.tripadvisor.com/Hotel_Review-g4118...   
4  https://www.tripadvisor.com/Hotel_Review-g4118...   

                                        reviews.text  \
0  Our experience at Rancho Valencia was absolute...   
1  Amazing place. Everyone was extremely warm and...   
2  We booked a 3 night stay at Rancho Valencia to...   
3  Currently in bed writing this for the past hr ...   
4  I live in Md and the Aloft is my Home away fro...   

                              reviews.title reviews.userCity  \
0           Best romantic vacation ever!!!!              NaN   
1                      Sweet sweet serenity              NaN   
2           Amazing Property and Experience              NaN   
3  Never again...beware, if you want sleep.         Richmond   
4                      ALWAYS GREAT STAY...           Laurel   

   reviews.userProvince reviews.username  \
0                   NaN            Paula   
1                   NaN                D   
2                   NaN              Ron   
3                    VA        jaeem2016   
4                    MD       MamaNiaOne   

                                          sourceURLs  \
0  http://www.hotels.com/ho125419/%25252525253Flo...   
1  http://www.hotels.com/ho125419/%25252525253Flo...   
2  http://www.hotels.com/ho125419/%25252525253Flo...   
3  http://www.yellowbook.com/profile/aloft-arunde...   
4  http://www.yellowbook.com/

In [11]:
df.columns

Index(['id', 'dateAdded', 'dateUpdated', 'address', 'categories',
       'primaryCategories', 'city', 'country', 'keys', 'latitude', 'longitude',
       'name', 'postalCode', 'province', 'reviews.date', 'reviews.dateSeen',
       'reviews.rating', 'reviews.sourceURLs', 'reviews.text', 'reviews.title',
       'reviews.userCity', 'reviews.userProvince', 'reviews.username',
       'sourceURLs', 'websites'],
      dtype='object')

In [13]:
x=df['reviews.text']

In [58]:
y=df['reviews.rating']
y = np.where(df['reviews.rating']>3,1,0)

In [18]:
from sklearn.model_selection import train_test_split

In [59]:
x_train,x_test,y_train,y_test = train_test_split(x,y)

In [60]:
x_train

632     Bad: I expected to have a much larger room tha...
6792    I recently rented a one bedroom Metropolitan S...
1540    Agree with previous review, renovation consist...
3605    The only negative was it was supposed to be a ...
2208    From the second you Valet your car, to check-i...
1667    Toilet paper is like sandpaper. Billed for cha...
4540    Such a good trip. Being there with my fiancee ...
9506    We spent one night here (in the suite) and wis...
9706    Do not expect New England-ish BB with antique ...
1344    This is a very nice hotel in a great downtown ...
2659    The room was very clean, but the AC could not ...
4183    Everything was great (clean, nice, free nice b...
567     Bad: Problems with door lock led to no respons...
1377    My husband and I have been coming to Atlanta f...
9078       Nice cute place to stay for a while. Loved it!
5278    It was a very nice, clean hotel with friendly ...
6565    Our first room had an interior door that led t...
8889    Room 1

In [61]:
y_train

array([1, 1, 0, ..., 1, 1, 0])

In [22]:
from sklearn.feature_extraction.text import CountVectorizer

In [138]:
vec = CountVectorizer(min_df=5,ngram_range=(1,5)).fit(x_train)

In [139]:
vec.get_feature_names()

['00',
 '00 am',
 '00 and',
 '00 for',
 '00 per',
 '00 pm',
 '000',
 '00am',
 '00pm',
 '10',
 '10 00',
 '10 15',
 '10 30',
 '10 day',
 '10 days',
 '10 min',
 '10 min walk',
 '10 mins',
 '10 minute',
 '10 minute walk',
 '10 minute walk to',
 '10 minutes',
 '10 minutes to',
 '10 off',
 '10 pm',
 '10 years',
 '100',
 '100 00',
 '101',
 '10am',
 '10pm',
 '10th',
 '11',
 '11 00',
 '11 30',
 '118',
 '11pm',
 '11th',
 '12',
 '13',
 '14',
 '15',
 '15 20',
 '15 day',
 '15 min',
 '15 minute',
 '15 minutes',
 '15 minutes from',
 '15 minutes to',
 '150',
 '16',
 '17',
 '18',
 '18th',
 '19',
 '1st',
 '20',
 '20 min',
 '20 mins',
 '20 minute',
 '20 minutes',
 '200',
 '200 night',
 '2012',
 '2014',
 '2015',
 '2015 and',
 '2016',
 '20th',
 '21',
 '22',
 '22nd',
 '23',
 '24',
 '24 hour',
 '24 hours',
 '25',
 '25 day',
 '25 minutes',
 '250',
 '27',
 '28',
 '29',
 '2am',
 '2nd',
 '2nd floor',
 '2nd time',
 '30',
 '30 am',
 '30 minute',
 '30 minutes',
 '30 pm',
 '300',
 '30am',
 '30pm',
 '30th',
 '32',
 '

In [140]:
vecv = vec.transform(x_train)

In [141]:
from sklearn.linear_model import LogisticRegression

In [142]:
model = LogisticRegression()

In [35]:
y_train = np.where(y_train>3,1,0)

In [143]:
model.fit(vecv,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [144]:
fnames  = np.array(vec.get_feature_names())

In [145]:
mc = model.coef_[0].argsort()

In [146]:
fnames[mc[:10]]

array(['dirty', 'worst', 'outdated', 'rude', 'basic', 'poor', 'smelled',
       'horrible', 'nice quiet', 'okay'], dtype='<U45')

In [147]:
fnames[mc[-11:-1]]

array(['love', 'exceptional', 'comfortable', 'always', 'good', 'enjoyed',
       'very clean', 'excellent', 'great', 'loved'], dtype='<U45')

In [153]:
model.predict(vec.transform(["The hotel is great in atmosphere but poor in serving and worst in hospitality"]))

array([0])

In [43]:
model.predict(vecv)

array([1, 0, 1, ..., 1, 1, 0])